language: r
sudo: false
cache: packages
dist: trusty

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --run-dontrun"

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=FALSE

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: Yvw9labkqW4fnOL4JbVnxlBSrK/Bme+acb5pHfoHLc5OkWilJ49JFGKgMpH63w1rZRMeuPkbGR7Ra1Ku9P28yLCl5uqpHHQge010gZ32e4jQLrTlSfewy8RioTrADqIWAFIIi2I/h1C7Rtd5I6QYuCNGdA58HScc/CIJVJxOywn4SYRKwiModD2lQXBXfpr+i9+JprHCoA1rBHqPiLqEkCn/6NoNOdruvVidMkR7GXidRmOI6us/SYF0T+QK9eQkcnRcdKo8WOu1PFY0PqU0IvTq5kV+H5insAKh3J0i/J5be1rBvL3jFAVIrhrGx0RrZ0ZcIWg7IvGaN463jv14d9KPl4aPbQsYzHs4bIshb8hoDXcmXyXPfJ4LfVnUGwW4jshE4QQvwaLoUtK7wl1PTleoKsjT/ZT4TK2RsdAde+ke6CspPfAQQWWt/ZGZLuR/5+mNbW9fZcN7p+8NR1nmYidGEXmDWd06wPIyimdU5FTSidS2RQjS/41Ts++1+sBa/S8h3dGIA2Xroij++BhQa+nij7NBPrzM7mveRFftCb+y+/Tf77QttDjsgdRTo1jfPQeuanJVgRS90HFi5swhC+ivk1485LLypVYBtmZ6QDS1WBirc6lf8B72nCsDleRKfIntagrXFw/U9R+b5/7cA0kpbqBM7Ftdabs2uHsQk0U=
